name: General Workflow

on:
  workflow_dispatch:
  pull_request:

jobs:
  execute-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Execute Dry Run for API
        run: robot --dryrun api

      - name: Execute Dry Run for Web
        run: robot --dryrun web

      - name: Execute Dry Run for Android
        run: robot --dryrun web

      - name: Execute Dry Run for iOS
        run: robot --dryrun ios

  post-pr-review-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Pull Request to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload-file-path: "./payload-slack-content.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
